In [2]:
l = [234234, 23 , 235, 654, 75, -13]

In [3]:
l

[234234, 23, 235, 654, 75, -13]

In [4]:
import numpy as np

In [5]:
a = np.array(l)

In [6]:
a

array([234234,     23,    235,    654,     75,    -13])

In [7]:
b = np.array([12,123,"asd",True])

In [8]:
b #they are in string

array(['12', '123', 'asd', 'True'], dtype='<U21')

In [9]:
l.pop()

-13

In [10]:
a.mean() #average of those values

39201.333333333336

In [11]:
c =a.copy()

In [12]:
c

array([234234,     23,    235,    654,     75,    -13])

In [13]:
c[0] = 0

In [14]:
c

array([  0,  23, 235, 654,  75, -13])

In [15]:
a

array([234234,     23,    235,    654,     75,    -13])